param=Background.java \
	  Blue.java \
	  Color.java \
	  Red.java \
	  Yellow.java

MainPrototype.class: MainPrototype.java $(param)
	javac MainPrototype.java

clean:
	rm -f *.class

exe:
	java MainPrototype
