param=AbstractFactory.java \
	  BlackApartment.java \
	  FactoryBlack.java \
	  FactoryWhite.java \
	  WhiteApartment.java \
	  Apartment.java \
	  BlackHouse.java \
	  FactoryCreator.java \
	  House.java \
	  Makefile \
	  WhiteHouse.java


MainAbstractFactory.class: MainAbstractFactory.java $(param)
	javac $<

clean:
	rm -f *.class

exe:
	java MainAbstractFactory
