all: Exc1 Exc2 Exc3 Exc4 Exc5 Exc6 Exc7 Exc8 Exc9 Exc10 Exc11 Exc12 Exc13 Exc14 \
	 Exc15 Exc16 Exc17 Exc18 Exc19 Exc20 Exc21 Exc22 Exc23 Exc24 Exc25 Exc26 \
	 Exc27 Exc28 Exc29 Exc30 Exc31

Exc1: Exc1.o
	ghc Exc1.o -o Exc1

Exc1.o: Exc1.hs
	ghc -c Exc1.hs

Exc2: Exc2.o
	ghc Exc2.o -o Exc2

Exc2.o: Exc2.hs
	ghc -c Exc2.hs

Exc3: Exc3.o
	ghc Exc3.o -o Exc3

Exc3.o: Exc3.hs
	ghc -c Exc3.hs

Exc4: Exc4.o
	ghc Exc4.o -o Exc4

Exc4.o: Exc4.hs
	ghc -c Exc4.hs

Exc5: Exc5.o
	ghc Exc5.o -o Exc5

Exc5.o: Exc5.hs
	ghc -c Exc5.hs

Exc6: Exc6.o
	ghc Exc6.o -o Exc6

Exc6.o: Exc6.hs
	ghc -c Exc6.hs

Exc7: Exc7.o
	ghc Exc7.o -o Exc7

Exc7.o: Exc7.hs
	ghc -c Exc7.hs

Exc8: Exc8.o
	ghc Exc8.o -o Exc8

Exc8.o: Exc8.hs
	ghc -c Exc8.hs

Exc9: Exc9.o
	ghc Exc9.o -o Exc9

Exc9.o: Exc9.hs
	ghc -c Exc9.hs

Exc10: Exc10.o
	ghc Exc10.o -o Exc10

Exc10.o: Exc10.hs
	ghc -c Exc10.hs

Exc11: Exc11.o
	ghc Exc11.o -o Exc11

Exc11.o: Exc11.hs
	ghc -c Exc11.hs

Exc12: Exc12.o
	ghc Exc12.o -o Exc12

Exc12.o: Exc12.hs
	ghc -c Exc12.hs

Exc13: Exc13.o
	ghc Exc13.o -o Exc13

Exc13.o: Exc13.hs
	ghc -c Exc13.hs

Exc14: Exc14.o
	ghc Exc14.o -o Exc14

Exc14.o: Exc14.hs
	ghc -c Exc14.hs

Exc15: Exc15.o
	ghc Exc15.o -o Exc15

Exc15.o: Exc15.hs
	ghc -c Exc15.hs

Exc16: Exc16.o
	ghc Exc16.o -o Exc16

Exc16.o: Exc16.hs
	ghc -c Exc16.hs

Exc17: Exc17.o
	ghc Exc17.o -o Exc17

Exc17.o: Exc17.hs
	ghc -c Exc17.hs

Exc18: Exc18.o
	ghc Exc18.o -o Exc18

Exc18.o: Exc18.hs
	ghc -c Exc18.hs

Exc19: Exc19.o
	ghc Exc19.o -o Exc19

Exc19.o: Exc19.hs
	ghc -c Exc19.hs

Exc20: Exc20.o
	ghc Exc20.o -o Exc20

Exc20.o: Exc20.hs
	ghc -c Exc20.hs

Exc21: Exc21.o
	ghc Exc21.o -o Exc21

Exc21.o: Exc21.hs
	ghc -c Exc21.hs

Exc22: Exc22.o
	ghc Exc22.o -o Exc22

Exc22.o: Exc22.hs
	ghc -c Exc22.hs

Exc23: Exc23.o
	ghc Exc23.o -o Exc23

Exc23.o: Exc23.hs
	ghc -c Exc23.hs

Exc24: Exc24.o
	ghc Exc24.o -o Exc24

Exc24.o: Exc24.hs
	ghc -c Exc24.hs

Exc25: Exc25.o
	ghc Exc25.o -o Exc25

Exc25.o: Exc25.hs
	ghc -c Exc25.hs

Exc26: Exc26.o
	ghc Exc26.o -o Exc26

Exc26.o: Exc26.hs
	ghc -c Exc26.hs

Exc27: Exc27.o
	ghc Exc27.o -o Exc27

Exc27.o: Exc27.hs
	ghc -c Exc27.hs

Exc28: Exc28.o
	ghc Exc28.o -o Exc28

Exc28.o: Exc28.hs
	ghc -c Exc28.hs

Exc29: Exc29.o
	ghc Exc29.o -o Exc29

Exc29.o: Exc29.hs
	ghc -c Exc29.hs

Exc30: Exc30.o
	ghc Exc30.o -o Exc30

Exc30.o: Exc30.hs
	ghc -c Exc30.hs

Exc31: Exc31.o
	ghc Exc31.o -o Exc31

Exc31.o: Exc31.hs
	ghc -c Exc31.hs

clean:
	rm -f *.o *.hi Exc*[0-9]
