all: Exc1 Exc2 Exc3 Exc4 Exc5 Exc6 Exc7 Exc8 Exc9

Exc1: Exc1.o
	ghc Exc1.o -o Exc1

Exc1.o: Exc1.hs
	ghc -c Exc1.hs

Exc2: Exc2.o
	ghc Exc2.o -o Exc2

Exc2.o: Exc2.hs
	ghc -c Exc2.hs

Exc3: Exc3.o
	ghc Exc3.o -o Exc3

Exc3.o: Exc3.hs
	ghc -c Exc3.hs

Exc4: Exc4.o
	ghc Exc4.o -o Exc4

Exc4.o: Exc4.hs
	ghc -c Exc4.hs

Exc5: Exc5.o
	ghc Exc5.o -o Exc5

Exc5.o: Exc5.hs
	ghc -c Exc5.hs

Exc6: Exc6.o
	ghc Exc6.o -o Exc6

Exc6.o: Exc6.hs
	ghc -c Exc6.hs

Exc7: Exc7.o
	ghc Exc7.o -o Exc7

Exc7.o: Exc7.hs
	ghc -c Exc7.hs

Exc8: Exc8.o
	ghc Exc8.o -o Exc8

Exc8.o: Exc8.hs
	ghc -c Exc8.hs

Exc9: Exc9.o
	ghc Exc9.o -o Exc9

Exc9.o: Exc9.hs
	ghc -c Exc9.hs

clean:
	rm -f *.o *.hi Exc[1-9]
