Taller1.pdf:  Taller1.tex 11*.tex 14.tex 15.tex 16*.tex 17.tex
	pdflatex Taller1.tex

clean:
	rm -f Taller1.pdf
	rm -f *.nav *.snm *.toc *.out *.dvi *.blg *.bbl *.aux *.log

exe:
	evince Taller1.pdf &
